### PR TITLE
feat: Make Popper instance available to child context

### PR DESCRIPTION
**Pull request by FezVrasta**
This allows this kind of usage:

```
const Demo = ({ close, children }) =>
  <span>
    <Target>👇</Target>
    <Portal>
      <ClickOutside onClickOutside={close}>
        <Popper>
          {({ popper }) =>
            <ResizeAware onResize={popper.scheduleUpdate}>
              {children} 👋
            </ResizeAware>
          }
        </Popper>
      </ClickOutside>
    </Portal>
  </span>
```

### CODE REVIEW

**Comment by souporserious** [comment]
Thanks! Thoughts on changing it to `popperInstance` or maybe just `instance` so it's more descriptive?

**Comment by FezVrasta** [comment]
Yes whatever makes sense to you it's fine.

**Comment by souporserious** [comment]
Talked with my coworkers and instead of passing the instance down. I'd feel better just passing down `scheduleUpdate`. This way someone doesn't get access to methods like `destroy` and we can keep those private for React to handle.

**Comment by souporserious** [comment]
I'll get an update out today with this functionality.

**Comment by FezVrasta** [comment]
Okay cool, that's fine too.

**Comment by lennerd** [comment]
What is the status here? I have a Popper element inside a container and I would like to update the relative position of the popper element to its target when the content of the container changes, due to a new position of the target element.

**Comment by lennerd** [comment]
Sorry, the `scheduleUpdate` function is already passed to a child function. Missed that. Also had an error in my structure. Everything is working fine now.

**Pull request closed without merging**
