### PR TITLE
fix: es5 build

### PR DESCRIPTION
**Pull request by Justkant**
This should fix the build issue :v:

### CODE REVIEW

**Comment by souporserious** [comment]
🙌 🙏

**Comment by supergibbs** [comment]
Something about the babel presets is messing up building with rollup. See https://github.com/reactstrap/reactstrap/issues/820#issuecomment-367577778

Works with the last few builds before v0.8.2

**Comment by Justkant** [comment]
@supergibbs thanks for the report, I'm going to look for a fix

**Comment by Justkant** [comment]
@supergibbs #93 should fix your issue

**Pull request merged**
