### PR TITLE
Added 16.* react peer dependency, made scripts platform independent

### PR DESCRIPTION
**Pull request by colindekker**
for platform indepedent development
Added rimraf and cross-env 

Dependency modifications:
Added ^16.0.0 to react and react-dom peer dependencies
downgrade glamor v3 as that has been abandoned.

### CODE REVIEW

**Comment by rkovalyov** [comment]
when it will be merged ?

**Comment by TheSharpieOne** [comment]
@rkovalyov probably with #59

**Comment by souporserious** [comment]
Sorry about the wait, I really appreciate this. Thank you 🙏

**Comment by colindekker** [comment]
It was a small change, thank you for the component!

**Pull request merged**
