### PR TITLE
add typescript definitions

### LINKED ISSUE #35: include typescript typings
@souporserious would you be open to including a `.d.ts` file in the NPM package for typescript consumers? i've been writing it locally and would be happy to contribute. 

there'd be some additional maintenance cost to keep the definitions updated as the API evolves, but I'll be happy to help out if you mention me in the future!

### PR DESCRIPTION
**Pull request by giladgray**
#### Requires https://github.com/FezVrasta/popper.js/pull/351 for latest definitions

### CODE REVIEW

**Comment by souporserious** [comment]
I'm not sure how TypeScript works, but I trust this is all good 😅 thank you!

**Comment by giladgray** [comment]
it actually depends on the _next_ (unreleased) version of popper.js so you may not want to ship it just yet.

fortunately, not shipping it is as easy as reverting my changes to [package.json](https://github.com/souporserious/react-popper/pull/40/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) -- you can still leave the file in repo but it wont be shipped to NPM.

**Comment by souporserious** [comment]
Dangit, too late 😓 should I still revert this?

**Comment by giladgray** [comment]
no need to revert, i've got it building just fine at https://github.com/palantir/blueprint/pull/1364 by including the `.d.ts` file for popper.js directly in our own source.

**Comment by FezVrasta** [comment]
I released yesterday a version with the type defs

**Pull request merged**
